consul_servers:
  hosts:
    consul-1:
      ansible_host: 10.50.1.10

consul_clients:
  hosts: {}

consul:
  children:
    consul_servers:
    consul_clients:

vault:
  hosts:
    vault-1:
      ansible_host: 10.50.1.20

bastion:
  hosts:
    bastion-1:
      ansible_connection: local
      bastion_private_ip: 10.50.1.5

#ensure single canonical bastion host in case of future HA setups and accidental multiple assignments of bastion_primary
bastion_primary:
  hosts:
    bastion-1: {}

k8s_controlplane:
  hosts:
    k8s_controlplane-1:
      ansible_host: 10.50.1.30


k8s_worker:
  hosts:
    k8s_worker-1:
      ansible_host: 10.50.1.41
